
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Library", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Library {


    /**
     * 
     * @return
     *     returns java.util.List<service.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBooks", targetNamespace = "http://service/", className = "service.GetAllBooks")
    @ResponseWrapper(localName = "getAllBooksResponse", targetNamespace = "http://service/", className = "service.GetAllBooksResponse")
    @Action(input = "http://service/Library/getAllBooksRequest", output = "http://service/Library/getAllBooksResponse")
    public List<Book> getAllBooks();

    /**
     * 
     * @param arg0
     * @return
     *     returns service.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookByName", targetNamespace = "http://service/", className = "service.GetBookByName")
    @ResponseWrapper(localName = "getBookByNameResponse", targetNamespace = "http://service/", className = "service.GetBookByNameResponse")
    @Action(input = "http://service/Library/getBookByNameRequest", output = "http://service/Library/getBookByNameResponse")
    public Book getBookByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBooksCheaperThan", targetNamespace = "http://service/", className = "service.GetBooksCheaperThan")
    @ResponseWrapper(localName = "getBooksCheaperThanResponse", targetNamespace = "http://service/", className = "service.GetBooksCheaperThanResponse")
    @Action(input = "http://service/Library/getBooksCheaperThanRequest", output = "http://service/Library/getBooksCheaperThanResponse")
    public List<Book> getBooksCheaperThan(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.Member
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerMember", targetNamespace = "http://service/", className = "service.RegisterMember")
    @ResponseWrapper(localName = "registerMemberResponse", targetNamespace = "http://service/", className = "service.RegisterMemberResponse")
    @Action(input = "http://service/Library/registerMemberRequest", output = "http://service/Library/registerMemberResponse")
    public Member registerMember(
        @WebParam(name = "arg0", targetNamespace = "")
        Member arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.Member
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMemberByID", targetNamespace = "http://service/", className = "service.GetMemberByID")
    @ResponseWrapper(localName = "getMemberByIDResponse", targetNamespace = "http://service/", className = "service.GetMemberByIDResponse")
    @Action(input = "http://service/Library/getMemberByIDRequest", output = "http://service/Library/getMemberByIDResponse")
    public Member getMemberByID(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "filterByGenre", targetNamespace = "http://service/", className = "service.FilterByGenre")
    @ResponseWrapper(localName = "filterByGenreResponse", targetNamespace = "http://service/", className = "service.FilterByGenreResponse")
    @Action(input = "http://service/Library/filterByGenreRequest", output = "http://service/Library/filterByGenreResponse")
    public List<Book> filterByGenre(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
